# Generated by Django 4.2.5 on 2023-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_questionanswer',
            name='status',
        ),
        migrations.AlterField(
            model_name='tbl_questionanswer',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbl_questionanswer',
            name='question',
            field=models.TextField(),
        ),
    ]
