# Generated by Django 4.2.4 on 2023-09-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapp', '0002_chatlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_questionanswer',
            name='answer',
            field=models.CharField(default='', max_length=800),
        ),
    ]
