# Generated by Django 4.2.5 on 2023-09-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapp', '0002_questionanswer_delete_tbl_questionanswer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionanswer',
            table='QuestionAnswer',
        ),
    ]
